AWSTemplateFormatVersion: 2010-09-09
Description: 'Create Lambda function and S3 bucket '
Resources:
  s3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: Private
  Lambda1:
    Type: "AWS::Lambda::Function"
    Properties: 
        Code:
            ZipFile: >
                def lambda_handler(event, context):
                return 'Hello World from Toluwase'
        Description: Assignment with Cloud Formation
        FunctionName: HelloWorldCF
        Handler: index.lambda_handler
        Role: arn:aws:iam::485596709887:role/lambda-role
        Runtime: python3.7
Outputs:
  Bucketname:
    Description: Bucket name
    Value: !Ref s3Bucket
  
